#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

export PATH="/home/maycon/.nvm/versions/node/v14.17.3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"

npm run test:coverage
