#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

#para resolver o problema do path dar ECHO $PATH e exportar ele aqui na linha 6

export PATH="/home/maycon/.nvm/versions/node/v14.17.3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"

npx lint-staged
